#ifndef _COMMAND_H
#define _COMMAND_H

enum opcode {
  PROGRAM_ENABLE =0,
  CHIP_ERASE,
  READ_STATUS,
  LOAD_PAGE_BUFFER,
  WRITE_CODE_PAGE,
  WRITE_CODE_PAGE_ERASE,
  READ_CODE_PAGE,
  WRITE_USER_FUSES,
  WRITE_USER_FUSES_ERASE,
  READ_USER_FUSES,
  WRITE_LOCK_BITS,
  READ_LOCK_BITS,
  WRITE_SIGNATURE_PAGE,
  WRITE_SIGNATURE_PAGE_ERASE,
  READ_SIGNATURE_PAGE,
  READ_ATMEL_SIGNATURE_PAGE,

  COMMAND_MAX
};



struct command {
  unsigned char op;
};


#endif
